config/routes.rb
Puretv::Application.routes.draw do
  get "contacts/lookup"

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "channels#show_root"

  match :terms, to: "pages#terms"
  match :welcome, to: "pages#welcome"
  match :yclogin, to: "pages#yc"

  resource :invites, only: [:new, :create]

  match "join/:token", to: "channel_invites#show", as: :join_channel
  match "join/:token/accept", to: "channel_invites#accept", as: :accept_join_channel

  # login
  scope :module => :auth do
    get   :login,   to: "sessions#new"
    post  :login,   to: "sessions#create"
    match :logout,  to: "sessions#destroy"

    get  :register,  to: "registrations#new"
    post :register,  to: "registrations#create"

    match "auth/:provider/check"    => "oauths#check"
    match "auth/:provider/callback" => "oauths#callback", :as => :auth_at_provider

    resources :password_resets do
      collection do
        match :confirmation
      end
    end
  end

  # channel management
  get "dashboard", :to => "manage/channels#index"
  scope "/me", :module => :manage, :as => :manage do
    get "settings", :to => "settings#edit"
    put "settings", :to => "settings#update"
    get "request/status/add_video", :to => "request_status#add_video"

    resources :likes, :only => [:index, :show, :create, :destroy]
    resources :airings, :only => [:show]

    get "feed/first",    :to => "feed#first"
    get "feed/:id/next", :to => "feed#next"

    get "lookup/:provider", :to => "contacts#lookup"
    get "following",        :to => "followers#following"

    resources :channels, :path => "streams" do
      collection do
        match :following
      end

      resources :memberships, only: [:index, :create, :destroy]
      resources :activities, only: :index
      resources :followers, only: :index

      resources :airings, :only => [:create, :destroy] do
        member do
          put :archive
          put :unarchive, :to => "airings#archive"
        end
      end

      resources :videos do
        collection do
          match :archived
          put :sort
        end
      end
    end

    resources :memberships, :only => [:create, :destroy]
  end

  resources :channels, :only => [:index] do
    member do
      match :chromeless, :to => "channels#show_chromeless"
      match :subscribe
      match :unsubscribe, :to => "channels#subscribe"
    end

    resources :videos, :only => [:show] do
      collection do
        get :first
      end
      member do
        get :notes
        get :next
      end
    end
  end

  resources :airings do
    resources :likes,    :only => [:create, :destroy]
    resources :comments, :only => [:create, :destroy]
  end

  scope "f" do
    match ":name/video", :to => "channels#feed", as: :feed_video
    match "/", :to => "channels#feed", as: :feed
  end

  scope ":name" do
    match :chromeless, :to => "channels#show_chromeless", as: :chromeless
    match "video", :to => "channels#show", as: :start_video
    #match ":v", :to => "channels#show"
    match "/", :to => "channels#show", as: :slug
  end

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  acts_as_paranoid

  BEST_SLUGS = {
    :news => ["ap", "aljazeeraenglish", "theyoungturks"],
    "best of the web" => ["devour", "laughingsquid"],
    :travel => ["lonelyplanet", "bbcearth", "natgeo"],
    :sports => ["grantlandnetwork", "redbull", "networka", "thrashermagazine"],
    :culture => ["vice", "booooooom", "jayz", "coolhunting", "complexmagazine", "iamother"],
    :food => ["foodwishes", "dudefood", "epicmealtime", "bbcfood"],
    :science => ["vsauce", "minutephysics", "asapscience"],
    :knowledge => ["tedtalks", "bbc", "mentalfloss"],
    :music => ["pitchforktv", "noisey", "lablogotheque"],
    :humor => ["theonion", "collegehumor", "funnyordie"],
    :tv => ["jimmykimmellive", "teamcoco", "ellen"]
  }

  belongs_to :creator, :class_name => "User"

  # airings
  has_many :airings, :conditions => "airings.state != 'archived'", :order => "position ASC, airings.created_at DESC"
  has_many :videos, :through => :airings, :order => "airings.created_at DESC"
  has_many :archived_airings, :class_name => "Airing", :conditions => "airings.state = 'archived'", :order => "position ASC, airings.created_at DESC"
  has_many :archived_videos, :source => :video,  :through => :archived_airings

  #has_many :activities, class_name: "Activity", as: :secondary_subject, :order => "created_at DESC"
  has_many :activities, :through => :airings, :source => :attachments,
    class_name: "Activity", :order => "created_at DESC"

  has_many :likes, :through => :airings

  has_many :subscriptions, :dependent => :destroy
  has_many :subscribers, :through => :subscriptions, source: :user

  has_many :memberships,   :dependent => :destroy
  has_many :members, through: :memberships, source: :user

  has_many :channel_invites

  validates :title, uniqueness: true, presence: true
  validates :slug,  uniqueness: { :case_sensitive => false }, presence: true, :format => {:with => /^[a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*$/}

  mount_uploader :cover_art, CoverArtUploader

  before_save :update_airings_count
  before_validation :downcase_slug

  scope :publik, where("private IS NULL").where("channels.airings_count > ?", 0)
  scope :explore, reorder("channels.airings_count DESC")
  scope :explore_for, lambda {|user| not_in = user.following_channels + user.channels; where("channels.id NOT IN (?)", not_in).explore}
  scope :omit_following, lambda {|user| not_in = user.following_channels + user.channels; where("channels.id NOT IN (?)", not_in)}


  def self.best
    channels = {}
    BEST_SLUGS.each do |key, value|
      channels[key] = Channel.where(:slug => value)
    end
    channels
  end

  def downcase_slug
    self.slug = self.slug.downcase if self.slug.present?
  end

  def parties
    [creator] + members
  end

  def activities
    Activity.where("(subject_type = 'Airing' and subject_id IN (?)) or (subject_type = 'Channel' and subject_id = (?))", airings, self.id)
  end

  def description
    (self[:description].blank? and airings.any?) ? "i.e. #{airings.first.title}" : self[:description]
  end

  def last_three_videos
    videos.limit(3)
  end

  # grab likes from yesterday
  def todays_likes
    dayEnd = DateTime.now.beginning_of_day
    dayStart = dayEnd - 1.day

    likes.where("likes.created_at > ? and likes.created_at < ?", dayStart, dayEnd)
  end

  def likes_from_last(duration)
   time_end = DateTime.now
   time_start = time_end - duration

   likes.where("likes.created_at > ? and likes.created_at < ?", time_start, time_end)
  end

  def all_airings
    airings + archived_airings
  end

  def self.default
    find(1)
  rescue ActiveRecord::RecordNotFound
    first
  end

  def subscription_for(user)
    subscriptions.find_by_user_id(user.id)
  end

  def subscribed_by?(user)
    ! Subscription.find_by_user_id_and_channel_id(user.id, self.id).nil?
  end

  def now_playing
    airings.first.video
  end

  def member?(user)
    memberships.where(:user_id => user.id).any? || user.owns?(self)
  end

  def has_airings?
    airings.any?
  end

  def favorited?(user)
    ! subscriptions.find(:first, :conditions => [ "user_id = ?", user.id]).nil?
  end

  def subscribed_by(user)
    s = subscriptions.create(:user_id => user.id)
    s.update_unread_count!
  end

  def gen_random_string
    if random_string.nil?
      chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
      string = ""
      1.upto(10) { |i| string << chars[rand(chars.size-1)] }
      self.random_string = string
    end
    random_string
  end

  def needs_crawl?
    false
  end

  # gets the next video in the order.  accepts an id.
  def next_video(current_id)
    @video_ids = airings.map {|a| a.video_id }

    @current_index = @video_ids.index current_id.to_i

    if @current_index
      next_index = (@current_index + 1) % self.videos.count
      Video.find(@video_ids[next_index])
    else
    # give the next video or the first if current_index not set.
      Video.find(@video_ids[rand(self.videos.count)])
    end
  end

  def next_airing(cid=nil,user=nil)
    next_airing_for_user(user) || next_airing_for_id(cid) || airings.first
  end

  def next_airing_for_user(user)
    return if user.blank?

    if airings.unread_by(user).any?
      next_unseen_airing_for_user user
    elsif subscribed_by? user
      next_since_last_seen_for_user user
    end
  end

  def next_airing_for_id(current_id)
    return if current_id.blank?
    return if ! airings.exists?(current_id)

    ids = airings.map {|a| a.id }

    current_index = ids.index current_id.to_i

    if current_index
      next_index = (current_index + 1) % self.airings.count
      airings.find(ids[next_index])
    else
      # give the next video or the first if current_index not set.
      airings.first
    end
  end

  def next_since_last_seen_for_user(user)
    subscription = self.subscription_for user
    if subscription
      next_airing_for_id subscription.last_played_id
    end
  end

  def next_unseen_airing_for_user(user)
    airings.unread_by(user).first
  end

  def find_airing_from_video_id(id)
    airings.find(:first, conditions: {video_id: id})
  end

  def channel_subscribers_count
    subscriptions.count
  end

  def as_json(options={})
    options = {
      methods: [:channel_subscribers_count],
      only: [:id, :title, :description, :cover_art, :slug]
    }.merge options
    super
  end

  def to_param
    slug
  end

  private

  def update_airings_count
    self.airings_count = airings.reload.count
  end
end

app/models/channel/facebook.rb
class Channel::Facebook < Channel
  
  def get_recent(number)
    MiniFB.fql(creator.authentications.find_by_provider("facebook").token, "SELECT attachment, message, post_id, actor_id FROM stream WHERE filter_key in (SELECT filter_key FROM stream_filter WHERE uid=me() AND type='newsfeed') AND strpos(attachment.href, 'youtube') > 0 AND created_time > 1262196000 LIMIT #{number}") 
  end
  
  def crawl(number)
    recently = get_recent(number)
    
    recently.each do |fbvid|
      vp = VideoProvider.new [fbvid.attachment.href]
      
      vp.get.each do |v_params|
        if v_params.delete(:success)
          unless v = Video.find_by_source_name_and_source_id(v_params[:source_name], v_params[:source_id])
            v = Video.create(v_params.merge({
              :provider_object_id => fbvid.post_id,
              :provider_user_id => fbvid.actor_id
            }))
          end
          self.airings.create :video_id => v.id
        end 
      end
      
    end
  end
  
  def needs_crawl?
    true
  end
  
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_filter :require_login, :only => [:subscribe]

  # Render mobile or desktop depending on User-Agent for these actions.
  before_filter :check_for_mobile, :only => [:feed, :show, :show_root]

  def index
    @channels = logged_in? ?
      Channel.publik.explore_for(current_user) :
      Channel.publik.explore

    respond_to do |format|
      format.json { render json: @channels.as_json }
    end
  end

  def feed
    if params[:v]
      @first_airing_id = params[:v]
    end

    if params[:welcome]
      @show_welcome = true
    end

    unless logged_in?
      if @first_airing_id.present?
        @first_airing = Airing.find @first_airing_id
        redirect_to start_video_path(@first_airing.channel.slug, v: @first_airing_id)
      else
        redirect_to login_path
      end
      return
    end

    @first_airing = current_user.unwatched_feed.first
    @channel_list = current_user.subscriptions
    @my_channels = current_user.channels

    set_title "Feed"

    render action: "show", layout: "player"
  end

  def show
    @channel = params.key?(:name) ?
      Channel.find_by_slug!(params[:name]) : nil

    if params[:v] and @channel.airings.exists? params[:v]
      @first_airing = Airing.find(params[:v])
      @first_airing_id = params[:v]
    else
      @first_airing = @channel.airings.first
    end

    if logged_in?
      @channel_list = current_user.subscriptions
      @my_channels = current_user.channels
    end

    set_title @first_airing ? @first_airing.title : @channel.title

    if @first_airing
      set_description @first_airing.description
    end

    render :layout => "player"

  rescue ActiveRecord::RecordNotFound
    redirect_to login_path
  end

  def show_root
    if logged_in?
      redirect_to feed_path
    else
      @channel = Channel.default
      redirect_to slug_path @channel.slug
    end
  end

  def show_chromeless
    @channel = Channel.find_by_slug!(params[:name])

    unless @channel.airings.count > 0
      redirect_to chromeless_path(default_channel.slug)
      return
    end

    set_title @channel.title
    render :layout => "player"

  rescue ActiveRecord::RecordNotFound
    redirect_to slug_path(Channel.default.slug)
  end

  def subscribe
    channel = Channel.find(params[:id])

    if channel.subscribed_by?(current_user)
      Subscription.find_by_channel_id_and_user_id(channel.id, current_user.id).destroy

      flash[:success] = "You've removed " + channel.title
      respond_to do |format|
        format.json {render json: {subscribed: false, count: channel.subscriptions.count }}
        format.html {redirect_to channel}
      end
    else
      subscription = current_user.subscriptions.create(:channel => channel)

      Activity.add :channel_subscribe,
        actor: subscription.user.primary_channel,
        subject: subscription,
        secondary_subject: subscription.channel

      respond_to do |format|
        format.json {render json: {subscribed: true, count: channel.subscriptions.count }}
        format.html do
          flash[:success] = "You have subscribed to this channel. "
          redirect_to slug_path(channel.slug)
        end
      end
    end
  end

  private

  def default_channel
    channel = logged_in? ? current_user.subscriptions.first : Channel.default
    channel || Channel.default
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
  def top_channel
    @top ||= Channel.order("subscriptions_count DESC, updated_at DESC").first
  end

  def is_top?(channel)
    top_channel.id == channel.id
  end
end

app/views/channels/_channel.html.haml
- if c.has_airings?
  %li.channel.clearfix{:class => "color#{index % 2 }"}
    .coverart= link_to image_tag(c.cover_art_url(:thumb_list)), channel_path(c)
    .content
      .title
        = link_to "#{c.title}", channel_path(c)
        %span.user= c.creator.username if c.creator
      .description= c.description
      %span.count= "+#{c.subscriptions.count}"
      - if logged_in?
        - if current_user.owns?(c)
          .star= link_to "edit", manage_channel_videos_path(c)
        - else
          .star= link_to c.favorited?(current_user) ? "yes" : "no", subscribe_channel_path(c)
  - index += 1

app/views/channels/_channel_list_item.html.haml
- sub_count = channel.subscription_for(current_user).unread_count

%li.channel.clearfix{class: (sub_count ? "unread" : "")}
  = link_to channel_path(channel) do
    .icon
      .unread-count= "#{sub_count}"
      = image_tag(channel.cover_art_url(:thumb_list))
    .title
      = channel.title
      %span.slug= channel.creator.username if channel.creator.present?
    .description= channel.description
    .actions
      - if current_user.owns?(channel)
      - else
        = link_to subscribe_channel_path(channel) do
          .action.star.subscribe Follow

app/views/channels/_menu.html.haml
#channel-menu
  - if logged_in?
    - if current_user.owns?(@channel)
      = link_to 'edit', manage_channel_videos_path(@channel)
    - else
      - if @channel.subscribed_by?(current_user)
        = link_to unsubscribe_channel_path(@channel) do
          &#9996;
      - else
        = link_to '+', subscribe_channel_path(@channel)
  - else
    = link_to '+', subscribe_channel_path(@channel)

app/views/channels/_player.html.haml
- if @first_airing
  - content_for :meta do
    = render :partial => "layouts/meta_video", :locals => { :og_type => "video.other",
      :og_title => "#{@first_airing.title} on moziy",
      :og_description => @first_airing.description,
      :og_url => start_video_path(@first_airing.channel.slug, v: @first_airing.id),
      :og_image => @first_airing.video.video_image_url(:thumb_list)}

#alert{style: "display:none"}
- if @first_airing
  %img{style: "position: absolute; top: -9999px", src: @first_airing.video.video_image_url }
#channel-modal.modal
#notes-modal.modal
#sharing-modal.modal
#restream-modal.modal
#add-modal.modal
#login-modal.modal
#invite-modal.modal
#channels-modal.modal
#image-modal.modal
#multiimage-modal.modal

#player
  .mask-affordance
  #youtube-player.player
    .mask
  #vimeo-player.player
    .mask
    #vimeo-dummy

#remote-control-pane.clearfix
#controls-pane
#current-pane-target-zone
  #current-pane
    #current-video
    #current-channel
    -##current-sharing.clearfix

app/views/channels/index.html.haml
#channel-manage
  #main-content.channel-list.list
    %ul#secondary-menu.clearfix
      %li{:class => @sort.nil? ? "active" : "" }= link_to "Following", root_path
      %li{:class => @sort == "watchers" ? "active" : "" }= link_to "Popular", root_path(:sort => "watchers")

    - if @sort.nil? and ! logged_in?
      %ul.channels
        %li.channel.clearfix{:id => "channel_#{@mosey_channel.id.to_s}", "data-channel-id" => @mosey_channel.id.to_s}
          .coverart= link_to image_tag(@mosey_channel.cover_art_url(:thumb_list)), channel_path(@mosey_channel)
          .content
            .title
              = link_to "#{@mosey_channel.title}", channel_path(@mosey_channel)
              %span.user= @mosey_channel.creator.username if @mosey_channel.creator
            .description= @mosey_channel.description
            %span.count= "+#{@mosey_channel.subscriptions.count}"

      #register
        %h2 Join mosey.tv to watch the best video channels online. It’s absolutely free.
        = form_for(@user, :url => register_path) do |f|
          - if @user.errors.any?
            #error_explanation
              %ul
                - @user.errors.full_messages.each do |msg|
                  %li= msg
          .field
            = f.label :username
            %br/
            = f.text_field :username
          .field
            = f.label :email
            %br/
            = f.text_field :email
          .field
            = f.label :password
            %br/
            = f.password_field :password
          .actions
            = f.submit "Sign Up", :class => "button primary"

    - else
      %ul.channels
        - index = 0
        - @channels.each do |c|
          - if c.has_airings?
            %li.channel.clearfix{:class => (logged_in? and c.favorited?(current_user)) ? "favorited": "", :id => "channel_#{c.id.to_s}", "data-channel-id" => c.id.to_s}
              .coverart= link_to image_tag(c.cover_art_url(:thumb_list)), channel_path(c)
              .content
                .title
                  = link_to "#{c.title}", channel_path(c)
                  %span.user= c.creator.username if c.creator
                .description= c.description
                %span.count= "+#{c.subscriptions.count}"
                - if logged_in?
                  .actions
                    = link_to subscribe_channel_path(c) do
                      .action.star.subscribe
                    - if current_user.owns?(c)
                      = link_to manage_channel_videos_path(c) do
                        .action.edit
            - index += 1
  #viewer
    %iframe#viewer-iframe{:width => "100%", :height => "100%", :frameborder => 0}

app/views/channels/new.html.haml
.full-col
  = form_for @channel do |f|
    .field
      = f.label :title
      = f.text_field :title
    .actions
      = f.submit 

app/views/channels/show.html.haml
= render partial: "player"

:javascript
  $(document).ready(function() {
    var current_user = #{current_user_json(@channel_list, @my_channels)}

    var bootstrap = {
      channel: #{@channel.to_json},
      current_user: current_user,
      first_airing_id: #{@first_airing_id.to_json},
      showWelcome: #{@show_welcome || false}
    };

    App.initialize(bootstrap);
  });

app/views/channels/show_chromeless.html.haml
#mute.on.chromeless
-##invite-modal.modal
#player.chromeless
  #youtube-player.player
    .mask
  #vimeo-player.player
    .mask
    #vimeo-dummy

:javascript
  $(document).ready(function() {

    var bootstrap = {
      channel: #{@channel.to_json},
      noInvite: true
    };

    App.initialize(bootstrap);
  });

app/views/channels/show_root.html.haml
#login-modal.modal
#invite-modal.modal

#player
  #youtube-player.player
    .mask
  #vimeo-player.player
    .mask
    #vimeo-dummy

#moziy-logo-splash
  .logo-moziy-big moziy

:javascript
  $(document).ready(function() {

    var bootstrap = {
      channel: #{@channel.to_json}
    }

    App.initialize(bootstrap);
  });