config/routes.rb
Puretv::Application.routes.draw do
  get "contacts/lookup"

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "channels#show_root"

  match :terms, to: "pages#terms"
  match :welcome, to: "pages#welcome"
  match :yclogin, to: "pages#yc"

  resource :invites, only: [:new, :create]

  match "join/:token", to: "channel_invites#show", as: :join_channel
  match "join/:token/accept", to: "channel_invites#accept", as: :accept_join_channel

  # login
  scope :module => :auth do
    get   :login,   to: "sessions#new"
    post  :login,   to: "sessions#create"
    match :logout,  to: "sessions#destroy"

    get  :register,  to: "registrations#new"
    post :register,  to: "registrations#create"

    match "auth/:provider/check"    => "oauths#check"
    match "auth/:provider/callback" => "oauths#callback", :as => :auth_at_provider

    resources :password_resets do
      collection do
        match :confirmation
      end
    end
  end

  # channel management
  get "dashboard", :to => "manage/channels#index"
  scope "/me", :module => :manage, :as => :manage do
    get "settings", :to => "settings#edit"
    put "settings", :to => "settings#update"
    get "request/status/add_video", :to => "request_status#add_video"

    resources :likes, :only => [:index, :show, :create, :destroy]
    resources :airings, :only => [:show]

    get "feed/first",    :to => "feed#first"
    get "feed/:id/next", :to => "feed#next"

    get "lookup/:provider", :to => "contacts#lookup"
    get "following",        :to => "followers#following"

    resources :channels, :path => "streams" do
      collection do
        match :following
      end

      resources :memberships, only: [:index, :create, :destroy]
      resources :activities, only: :index
      resources :followers, only: :index

      resources :airings, :only => [:create, :destroy] do
        member do
          put :archive
          put :unarchive, :to => "airings#archive"
        end
      end

      resources :videos do
        collection do
          match :archived
          put :sort
        end
      end
    end

    resources :memberships, :only => [:create, :destroy]
  end

  resources :channels, :only => [:index] do
    member do
      match :chromeless, :to => "channels#show_chromeless"
      match :subscribe
      match :unsubscribe, :to => "channels#subscribe"
    end

    resources :videos, :only => [:show] do
      collection do
        get :first
      end
      member do
        get :notes
        get :next
      end
    end
  end

  resources :airings do
    resources :likes,    :only => [:create, :destroy]
    resources :comments, :only => [:create, :destroy]
  end

  scope "f" do
    match ":name/video", :to => "channels#feed", as: :feed_video
    match "/", :to => "channels#feed", as: :feed
  end

  scope ":name" do
    match :chromeless, :to => "channels#show_chromeless", as: :chromeless
    match "video", :to => "channels#show", as: :start_video
    #match ":v", :to => "channels#show"
    match "/", :to => "channels#show", as: :slug
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
  has_many :airings, :dependent => :destroy
  has_many :likes, through: :airings

  serialize :source_meta, JSON

  validates :title, :presence => true
  validates :body, :presence => true
  validates :source_name, :presence => true, :uniqueness => {:scope => [:source_id]}
  validates :source_id, :presence => true

  mount_uploader :video_image, VideoImageUploader

  def note_count
    airings.count + likes.count
  end

  def gen_random_string
    if random_string.nil?
      chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
      string = ""
      1.upto(10) { |i| string << chars[rand(chars.size-1)] }
      self.random_string = string
    end
    random_string
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  include AiringsHelper

  before_filter :set_channel

  def first
    # grab the video only if it still exists in the player
    # else send the first video in the channel
    video = if logged_in?
              @channel.next_airing(nil,current_user)
            else
              @channel.airings.first
            end

    if logged_in? and video
      mark_as_read video
    end

    render json: airing_json(video)
  end

  def show
    video = @channel.airings.find params[:id]

    if logged_in?
      mark_as_read video
    end

    render json: airing_json(video)
  end

  def next
    if logged_in?
      if former_video = @channel.airings.find(params[:id])
        mark_as_read former_video
      end
    end

    video = @channel.next_airing(params[:id], (logged_in? ? current_user : nil))

    render json: airing_json(video)
  end

  def notes
    video = @channel.airings.find(params[:id])
    render json: {notes: video.notes}
  end

  private

  def set_channel
    @channel = Channel.includes(:airings => :video).find(params[:channel_id])
  end
end

app/views/videos/edit.html.haml
.full-col
  = form_for [@channel, @video] do |f|
    .field
      = f.label :title
      %br
      = f.text_field :title
    .field
      = f.label :body
      %br
      = f.text_area :body
    .field
      = f.label :description
      %br
      = f.text_area :description
    .actions
      = f.submit

app/views/videos/index.html.haml
.full-col
  = link_to 'settings', edit_channel_path(@channel)
  %br
  %ul.videos
    - @channel.airings.each do |a|
      %li.video{:id => "video_#{a.video_id.to_s}"}
        .title= a.video.title
        .actions
          = link_to 'edit', edit_channel_video_path(@channel, a.video)
          = link_to 'delete', [@channel, a.video], :method => :delete
:javascript
  $(".videos").sortable({items: ".video", axis: "y", cursor: "move", 
    update: function() {
      $.post("/channels/#{@channel.id}/videos/sort", "_method=put&"+ $(this).sortable("serialize"))
    }})

app/views/videos/new.html.haml
.full-col
  = form_for [@channel, @video], :url => channel_videos_path(@channel) do |f|
    .field
      %strong Add Videos
      = label_tag :links, 'Enter a comma separated list of links'
      %br
      = text_area_tag :links
    .actions
      = f.submit "Add to Channel"
      = link_to 'cancel', @channel