config/routes.rb
Puretv::Application.routes.draw do
  get "contacts/lookup"

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "channels#show_root"

  match :terms, to: "pages#terms"
  match :welcome, to: "pages#welcome"
  match :yclogin, to: "pages#yc"

  resource :invites, only: [:new, :create]

  match "join/:token", to: "channel_invites#show", as: :join_channel
  match "join/:token/accept", to: "channel_invites#accept", as: :accept_join_channel

  # login
  scope :module => :auth do
    get   :login,   to: "sessions#new"
    post  :login,   to: "sessions#create"
    match :logout,  to: "sessions#destroy"

    get  :register,  to: "registrations#new"
    post :register,  to: "registrations#create"

    match "auth/:provider/check"    => "oauths#check"
    match "auth/:provider/callback" => "oauths#callback", :as => :auth_at_provider

    resources :password_resets do
      collection do
        match :confirmation
      end
    end
  end

  # channel management
  get "dashboard", :to => "manage/channels#index"
  scope "/me", :module => :manage, :as => :manage do
    get "settings", :to => "settings#edit"
    put "settings", :to => "settings#update"
    get "request/status/add_video", :to => "request_status#add_video"

    resources :likes, :only => [:index, :show, :create, :destroy]
    resources :airings, :only => [:show]

    get "feed/first",    :to => "feed#first"
    get "feed/:id/next", :to => "feed#next"

    get "lookup/:provider", :to => "contacts#lookup"
    get "following",        :to => "followers#following"

    resources :channels, :path => "streams" do
      collection do
        match :following
      end

      resources :memberships, only: [:index, :create, :destroy]
      resources :activities, only: :index
      resources :followers, only: :index

      resources :airings, :only => [:create, :destroy] do
        member do
          put :archive
          put :unarchive, :to => "airings#archive"
        end
      end

      resources :videos do
        collection do
          match :archived
          put :sort
        end
      end
    end

    resources :memberships, :only => [:create, :destroy]
  end

  resources :channels, :only => [:index] do
    member do
      match :chromeless, :to => "channels#show_chromeless"
      match :subscribe
      match :unsubscribe, :to => "channels#subscribe"
    end

    resources :videos, :only => [:show] do
      collection do
        get :first
      end
      member do
        get :notes
        get :next
      end
    end
  end

  resources :airings do
    resources :likes,    :only => [:create, :destroy]
    resources :comments, :only => [:create, :destroy]
  end

  scope "f" do
    match ":name/video", :to => "channels#feed", as: :feed_video
    match "/", :to => "channels#feed", as: :feed
  end

  scope ":name" do
    match :chromeless, :to => "channels#show_chromeless", as: :chromeless
    match "video", :to => "channels#show", as: :start_video
    #match ":v", :to => "channels#show"
    match "/", :to => "channels#show", as: :slug
  end

end

app/views/layouts/_analytics.html.haml
:javascript
  window.twttr = (function (d,s,id) {
    var t, js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return; js=d.createElement(s); js.id=id;
    js.src="//platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs);
    return window.twttr || (t = { _e: [], ready: function(f){ t._e.push(f) } });
  }(document, "script", "twitter-wjs"));

:javascript
  (function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==
  typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,
  e,d])};b.__SV=1.2}})(document,window.mixpanel||[]);
  mixpanel.init("#{Rails.configuration.mixpanel_key}");

- if logged_in?
  - name_tag = "#{current_user.primary_channel.slug} #{current_user.email}"

  - if flash[:new_user]
    :javascript
      mixpanel.alias(#{current_user.id})
      mixpanel.track("User:Signup")
  - else
    :javascript
      mixpanel.identify(#{current_user.id})

  :javascript
    mixpanel.name_tag("#{name_tag}")

    mixpanel.people.set({
      "$email": "#{current_user.email}",
      "$created": #{current_user.created_at.to_json},
      "$username": "#{current_user.username}",
      "channels": "#{current_user.managing_channels_slugs}",
      "likes": #{current_user.likes.count},
      "following": #{current_user.subscriptions.count}
    })

:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', "#{Rails.configuration.ga_key}"]);
  _gaq.push(['_trackPageview']);

  _gaq.push(['_setCustomVar', 1, 'Logged in', #{ current_user.blank? ? "'no'" : "'yes'" }, 2]);
  _gaq.push(['_setCustomVar', 2, 'Member', #{ current_user.blank? ? "'no'" : "'yes'" }, 1]);
  _gaq.push(['_setCustomVar', 3, 'Join month', #{ current_user.blank? ? "'0'" : "'#{current_user.created_at.month}'" }, 1]);
  _gaq.push(['_setCustomVar', 4, 'Join year', #{ current_user.blank? ? "'0'" : "'#{current_user.created_at.year}'" }, 1]);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/layouts/_facebook.html.haml
#fb-root
:javascript
  window.fbAsyncInit = function() {
    // init the FB JS SDK
    FB.init({
      appId      : '442289749178796', // App ID from the App Dashboard
      status     : true, // check the login status upon init?
      cookie     : true, // set sessions cookies to allow your server to access the session?
      xfbml      : true  // parse XFBML tags on this page?
    });

    // Additional initialization code such as adding Event Listeners goes here

  };

  // Load the SDK's source Asynchronously
  // Note that the debug version is being actively developed and might 
  // contain some type checks that are overly strict. 
  // Please report such bugs using the bugs tool.
  (function(d, debug){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all" + (debug ? "/debug" : "") + ".js";
     ref.parentNode.insertBefore(js, ref);
   }(document, /*debug*/ false));

app/views/layouts/_meta.html.haml
%meta{name: "title", content: title }
%meta{:name => "keywords", :content => t("meta.keywords")}

- if content_for? :meta
  = content_for :meta
- else
  %meta{:name => "description", :content => description}
  %meta{:property => "fb:app_id", :content => "442289749178796"}
  %meta{:property => "og:site_name", :content => t("meta.facebook.site_name")}

app/views/layouts/_meta_video.html.haml
- unless og_type.nil?
  %meta{:property => "og:type", :content => og_type}
- unless og_title.nil?
  %meta{:property => "og:title", :content => og_title}
- unless og_image.nil?
  %meta{:property => "og:image", :content => og_image}
- unless og_description.nil?
  %meta{:property => "og:description", :content => og_description}
- unless og_url.nil?
  %meta{:property => "og:url", :content => og_url}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title
    %link{ :rel => "shortcut icon", :href => "/assets/fallback/thumb_favicon_default.jpg", :type => "image/x-icon"}
    = render "layouts/meta"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render "layouts/analytics"

  %body#flipside{:class => body_id}
    = render "layouts/facebook"
    #stage
      .container
        %header.clearfix
          %h1= link_to "mosey", manage_channel_path(current_user.primary_channel)
          %nav.session
            %ul
              %li
                = link_to feed_path do
                  %i.watch-moziy-button
              - if logged_in?
                %li.stream-selector.dropdown.clearfix
                  %i.header-more.dropdown-toggle
                  .stream-name.dropdown-toggle
                    - if @channel.present?
                      = "/#{@channel.slug}"
                    - else
                      = "your channels"
                  %ul.submenu
                    - current_user.managing_channels.each do |channel|
                      %li.channel-item.menu-item
                        = link_to manage_channel_path(channel) do
                          = image_tag channel.cover_art_url(:thumb_favicon), width: 16, height: 16
                          = "/#{channel.slug}"
                    %li.menu-item= link_to "Create a New Stream", new_manage_channel_path
                %li
                  = link_to manage_settings_path do
                    -#Settings
                    %i.header-settings
                %li
                  = link_to logout_path do
                    -#Log out
                    %i.header-logout
              - else
                %li= link_to 'Log in', login_path
                %li= link_to 'Join', root_path
        %section#main
          %section#sidebar
            - if content_for? :sidebar
              = content_for :sidebar
            %ul.sidebar-menu.clearfix
              %li{:class => current_page?(manage_likes_path) ? "active" : "" }
                = link_to manage_likes_path, :class => "primary" do
                  %span.count= current_user.likes.count
                  = "Likes"
              %li{:class => current_page?(manage_following_path) ? "active" : "" }
                = link_to manage_following_path do
                  %span.count= current_user.following_channels.count
                  = "Following"
          %section#main-content
            = yield

    :javascript
      $(document).ready(function() {
        $(".dropdown-toggle").dropdown();
      });

app/views/layouts/email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <table border="0" cellspacing="0" cellpadding="0" align="center" style="width:640px;padding-left:20px;padding-right:20px; font-family: Helvetica, Arial, Sans-Serif">
      <tbody>
        <tr>
          <td style="padding: 20px 0;">
            <img src="http://www.moziy.com/assets/moziy-logo-2.png" alt="moziy" />
          </td>
        </tr>
        <tr>
          <td>
            <%= yield %>
          </td>
        </tr>
        <tr>
          <td style="padding: 20px 0;">
            <p style="font-size: 11px; color: #999;"><%= link_to "Unsubscribe from these emails", manage_settings_url %></p>
          </td>
        </tr>
      </tbody>
    </table>
  </body>
</html>

app/views/layouts/noheader.html.haml
!!!
%html
  %head
    %title= title
    %link{ :rel => "shortcut icon", :href => "/assets/fallback/thumb_favicon_default.jpg", :type => "image/x-icon"}
    = render "layouts/meta"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render "layouts/analytics"

  %body#welcome{:class => body_id}
    = render "layouts/facebook"
    .container
      = yield
    - if content_for? :footer
      = content_for :footer

app/views/layouts/player.html.haml
!!!
%html{lang: "en"}
  %head
    %title= title
    %link{ :rel => "shortcut icon", :href => "/assets/fallback/thumb_favicon_default.jpg", :type => "image/x-icon"}
    = render "layouts/meta"
    = stylesheet_link_tag    "player"
    = javascript_include_tag "player"
    = csrf_meta_tags
    = render "layouts/analytics"

  %body#stage{:class => body_id}
    = render "layouts/facebook"
    = yield

app/views/layouts/session.html.haml
!!!
%html
  %head
    %title= title
    %link{ :rel => "shortcut icon", :href => "/assets/fallback/thumb_favicon_default.jpg", :type => "image/x-icon"}
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render "layouts/analytics"
  %body#flipside{:class => body_id}
    .container
      %header.clearfix
        %h1= link_to "mosey", root_path
        %nav.session
          %ul
            - if logged_in?
              %li= link_to 'Log out', logout_path
            - else
              %li= link_to 'Join', register_path
              %li= link_to 'Log in', login_path
      %section#main
        - flash.each do |key, value|
          .flash.alert.alert-{:class => key} #{value}
        = yield